apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "serverless-drupal.fullname" . }}-config
data:
  uploads.ini: |
    file_uploads = On
    memory_limit = {{ .Values.drupal.php.memoryLimit }}
    upload_max_filesize = {{ .Values.drupal.php.uploadMaxFilesize }}
    post_max_size = {{ .Values.drupal.php.postMaxSize }}
    max_execution_time = {{ .Values.drupal.php.maxExecutionTime }}
  bootstrap.sh: |
    {{- .Files.Get "files/bootstrap.sh" | nindent 4 }}
  database.php: |
    {{- .Files.Get "files/database.php" | nindent 4 }}
